In [1]:
import pandas as pd

C:\anaconda3\envs\python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\anaconda3\envs\python39\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\anaconda3\envs\python39\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
import numpy as np

In [3]:
Expression = pd.read_csv('BL--ExpressionData.csv', index_col=0, header=0)

In [4]:
Expression

,RamDA_mESC_00h_A04,RamDA_mESC_00h_A05,RamDA_mESC_00h_A06,RamDA_mESC_00h_A07,RamDA_mESC_00h_A08,RamDA_mESC_00h_A09,RamDA_mESC_00h_A12,RamDA_mESC_00h_B01,RamDA_mESC_00h_B02,RamDA_mESC_00h_B03,...,RamDA_mESC_72h_H03,RamDA_mESC_72h_H04,RamDA_mESC_72h_H05,RamDA_mESC_72h_H06,RamDA_mESC_72h_H07,RamDA_mESC_72h_H08,RamDA_mESC_72h_H09,RamDA_mESC_72h_H10,RamDA_mESC_72h_H11,RamDA_mESC_72h_H12
TFAP4,0.514936,0.335947,0.508435,0.697219,0.235312,0.498715,0.505070,0.745242,0.745393,0.411572,...,0.065423,0.172102,0.445232,0.066194,0.129828,0.127203,0.408109,0.261884,0.301740,0.136730
SERPINB6C,1.377358,0.590133,0.531965,0.035018,1.421321,0.258996,0.513742,0.000000,0.035627,1.120317,...,2.146921,1.913811,2.173503,1.425083,1.422347,2.273834,0.825571,1.926336,1.969107,1.698734
TSPAN4,0.414227,1.267507,0.926676,0.708037,1.246819,0.655428,1.021455,0.813484,0.291647,0.644664,...,2.210271,1.466620,2.405487,2.246221,1.321424,1.750635,2.762029,2.032041,1.058757,1.312247
HTT,1.029369,0.767425,1.331583,1.099327,1.072096,1.104093,0.448943,0.824893,1.085151,0.966714,...,1.238196,1.657504,0.823224,1.533503,1.321566,1.120691,1.497078,1.443474,0.880993,1.223954
TCEA3,2.015302,1.876993,2.107479,1.267984,1.579593,1.358221,1.641453,1.737009,1.945687,1.732088,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.221178,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SPRY4,2.578243,1.391438,0.228373,1.794874,1.950271,2.337653,1.548538,1.529609,2.566589,2.255562,...,0.993596,0.000000,0.000000,0.048402,0.000000,0.000000,0.000000,0.000000,0.000000,0.361580
CRYAB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.221348,0.040632,0.000000,...,0.529874,0.221160,0.979082,1.797011,1.874824,1.427108,1.128739,1.478128,0.354393,1.659406
PLOD1,0.866855,1.069065,1.560507,1.185174,1.147226,0.902120,0.991757,0.709508,1.516369,0.739564,...,2.920509,3.406331,3.355428,2.650931,2.436956,3.264590,3.532243,3.530906,3.078550,3.657190
PNP,2.962616,2.833886,2.468585,2.165731,2.726895,2.057024,3.015614,2.747509,2.554672,2.403275,...,1.266934,0.830787,0.376090,1.055491,1.545152,0.290701,0.167298,1.169047,1.037633,0.990300
HIVEP2,0.000000,0.000000,0.000000,0.004436,0.000000,0.000000,0.018925,0.027397,0.000000,0.063947,...,0.000000,0.246848,0.000000,0.256125,0.146804,0.255583,0.000000,0.075621,0.000000,0.000000

In [5]:
SE_data = pd.read_csv('muti_data/new_mouse_sequeezefeature1.csv', index_col = 0, header = 0)

In [6]:
final_name = Expression.index.values

In [7]:
TF_500_SE = SE_data.loc[final_name]

In [8]:
TF_500_SE

,Dim_1,Dim_2,Dim_3,Dim_4,Dim_5,Dim_6,Dim_7,Dim_8,Dim_9,Dim_10,...,Dim_759,Dim_760,Dim_761,Dim_762,Dim_763,Dim_764,Dim_765,Dim_766,Dim_767,Dim_768
gene,,,,,,,,,,,,,,,,,,,,,
TFAP4,0.581641,0.269358,0.638474,0.412199,0.452681,0.139406,0.002823,0.057336,0.430972,0.125589,...,0.223519,-0.024531,0.586800,-0.669095,0.521123,0.014304,0.400978,0.548911,0.387451,0.711715
SERPINB6C,0.464863,0.161330,0.758633,0.263901,0.470696,0.187723,-0.015728,-0.006342,0.309139,0.019661,...,-0.024410,-0.251390,0.494603,-0.175750,0.351282,0.178013,0.449847,0.406360,0.285570,0.948790
TSPAN4,0.545205,0.154685,0.717109,0.383206,0.434275,0.140607,0.007311,0.042154,0.404315,0.015215,...,0.178889,-0.115804,0.498401,-0.692949,0.506625,0.065118,0.398045,0.480990,0.317717,0.751957
HTT,1.452999,-0.675963,0.286285,0.420181,0.283593,0.469724,-0.782212,-0.588005,-0.596541,0.269895,...,0.139141,0.405570,1.898859,0.889990,1.823499,0.259560,1.425640,0.144849,0.992360,2.760624
TCEA3,0.573232,0.323081,0.731344,0.271136,0.556976,0.093511,0.029066,0.004973,0.338383,0.081173,...,-0.037997,-0.123403,0.648125,-0.286431,0.440822,0.184122,0.495274,0.443091,0.250085,0.941727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SPRY4,1.495202,-0.210942,0.582597,0.712064,0.223922,0.521962,-0.551840,-0.137644,-0.209730,0.201584,...,0.049100,0.015538,1.092819,-0.060648,1.152072,-0.008615,1.013850,0.471261,0.555014,1.414169
CRYAB,0.522707,0.311897,0.764783,0.372717,0.544754,0.017949,-0.086069,-0.165785,0.483221,-0.037901,...,0.109858,-0.220131,0.557284,-0.464235,0.387282,0.095979,0.455108,0.496353,0.268869,0.741359
PLOD1,1.309038,0.064224,0.880491,0.603456,0.118851,0.533921,-0.223220,0.098682,0.295622,0.123799,...,-0.012901,0.119194,0.890484,-0.443523,0.957311,0.056955,0.857568,0.581941,0.399062,1.194420
PNP,1.177455,0.041443,0.725231,0.459248,0.140101,0.614837,-0.147920,0.117929,0.470637,0.065933,...,-0.015858,0.131310,0.727992,-0.335569,0.866224,0.022635,0.716288,0.468126,0.312504,0.954849
HIVEP2,1.411352,-0.832122,0.059423,0.277763,0.222343,0.441236,-0.924009,-0.706871,-0.734187,0.341563,...,0.289663,0.724433,2.174244,1.295648,2.248929,0.486755,1.687221,0.037269,1.121604,3.369053

In [9]:
TF_500_SE.to_csv('BL-SequenceData.csv')

In [10]:
SM_data = pd.read_csv('muti_data/mouse_NLP_feature.csv', index_col = 0, header = 0)

In [11]:
TF_500_SM = SM_data.loc[final_name]

In [12]:
TF_500_SM

,Dim_1,Dim_2,Dim_3,Dim_4,Dim_5,Dim_6,Dim_7,Dim_8,Dim_9,Dim_10,...,Dim_759,Dim_760,Dim_761,Dim_762,Dim_763,Dim_764,Dim_765,Dim_766,Dim_767,Dim_768
gene,,,,,,,,,,,,,,,,,,,,,
TFAP4,0.771732,0.009205,-0.118106,0.090280,-0.490969,-0.226491,0.094691,0.161636,0.075320,-0.086361,...,0.257445,0.236878,-0.170486,0.022328,-0.083489,0.365184,0.017491,-0.133263,-0.040854,-0.261977
SERPINB6C,0.634615,-0.005742,-0.198327,0.061273,-0.442400,-0.167792,0.422649,0.093886,-0.026962,0.127811,...,0.035790,0.155640,-0.089358,-0.038736,-0.014805,0.250031,0.192222,-0.208525,-0.003262,-0.157702
TSPAN4,0.634197,0.233803,-0.114226,0.267630,-0.289174,-0.148145,0.213620,0.403800,0.160208,-0.019708,...,0.041629,0.220398,-0.112260,-0.028502,-0.071912,0.451222,0.076135,-0.123543,0.115567,-0.094143
HTT,0.239298,-0.010509,-0.298976,-0.026065,-0.635071,0.353789,0.303633,0.474418,0.118301,0.278483,...,0.174461,0.272252,-0.157057,-0.259669,0.034294,0.340422,0.115478,-0.507944,0.257183,-0.065028
TCEA3,0.591722,0.077886,-0.250749,0.075648,-0.267101,0.087206,0.079057,0.219525,-0.045006,0.133960,...,0.260714,0.425642,0.263837,0.072419,-0.143899,0.160760,-0.034724,-0.226845,0.093226,-0.160269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SPRY4,0.685963,0.169933,-0.317045,-0.021791,-0.266017,0.048022,0.225806,0.136363,-0.066144,0.100691,...,0.184451,0.406819,0.107791,0.176879,-0.327816,0.026107,0.077324,-0.397674,0.178381,-0.095384
CRYAB,0.449854,0.046280,-0.046396,0.328561,-0.642139,0.058110,0.310467,0.049456,0.382192,0.154116,...,0.231714,0.410804,0.034311,-0.246237,-0.248746,0.337447,0.273821,-0.008326,0.126948,-0.178598
PLOD1,0.539738,0.155501,-0.178893,0.059669,-0.376065,-0.070498,0.210843,0.359758,0.121178,0.178065,...,0.179955,0.231294,-0.002506,0.099765,-0.223564,0.053558,0.069986,-0.091907,0.157824,-0.228136
PNP,0.569707,0.043418,-0.253606,-0.121628,-0.399041,0.024982,0.118566,0.260073,-0.093633,-0.059588,...,0.267397,0.536357,-0.062039,0.228342,-0.241653,0.126013,-0.078010,-0.135203,0.181960,0.010761
HIVEP2,0.590987,0.126552,-0.289842,0.108100,-0.411231,-0.199359,0.314003,0.381383,0.095711,0.069185,...,0.137666,0.168100,-0.252192,0.070179,-0.071503,0.040275,0.195083,-0.199149,0.083997,-0.264946

In [13]:
TF_500_SM.to_csv('BL-SemanticsData.csv')